apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: code-server
  namespace: workshopctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: code-server
  namespace: workshopctl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-server
  namespace: workshopctl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: workshopctl
  labels:
    app: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      serviceAccountName: code-server
      containers:
      - image: luxas/k8s-web-ide:v4.3.0
        # TODO: In the future: ghcr.io/cloud-native-nordics/k8s-web-ide:v4.3.0
        imagePullPolicy: Always
        name: code-server
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: TUTORIALS_REPO
          valueFrom:
            secretKeyRef:
              name: workshopctl
              key: TUTORIALS_REPO
        - name: TUTORIALS_DIR
          valueFrom:
            secretKeyRef:
              name: workshopctl
              key: TUTORIALS_DIR
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: workshopctl
              key: CLUSTER_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: workshopctl
spec:
  selector:
    app: code-server
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server
  namespace: workshopctl
  annotations:
    # Force a short TTL so that DNS record changes can propagate faster
    external-dns.alpha.kubernetes.io/ttl: "30s"
spec:
  ingressClassName: traefik
  rules:
  - host: "{{ .Values.workshopctl.CLUSTER_DOMAIN }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server
            port:
              number: 80
