apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: workshopctl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: workshopctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: workshopctl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: workshopctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.17
        args:
        - --source=service
        - --source=ingress
        - --domain-filter={{ .Values.workshopctl.rootDomain }}. # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider={{ .Values.workshopctl.provider }}
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --registry=txt
        - --txt-owner-id=workshopctl
        env:
        - name: PROVIDER_SERVICEACCOUNT
          valueFrom:
            secretKeyRef:
              name: workshopctl
              key: PROVIDER_SERVICEACCOUNT
